apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: django
  name: django
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: postgres-credentials
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: postgres-credentials
          - name: POSTGRES_HOST
            value:
              127.0.0.1:5432
          image: gcr.io/pipeline-tutorial-231718/pipeline:acca323293426202f45b435ffa06f546cd420211
          name: django
          ports:
          - containerPort: 8000
        - name: cloudsql-proxy
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: postgres-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-credentials
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          #command: ["/cloud_sql_proxy",
          #          "-instances=<INSTANCE_CONNECTION_NAME>=tcp:5432",
          #          "-credential_file=/secrets/cloudsql/credentials.json"]
          command: ["cloudsqlpostgres",
                    "host=pipeline-tutorial-231718:us-west1 user=${POSTGRES_USER} dbname=postgres-db password=${POSTGRES_PASSWORD} sslmode=disable"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
