apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: django
  name: django
  namespace: default
spec:
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: dbname
              name: cloudsql-db-credentials
        image: gcr.io/pipeline-tutorial-231718/pipeline:7bdba3abf3be675a9c4c99cbf3409544e2d46cde
        name: django
        ports:
        - containerPort: 8000
      - command:
        - /cloud_sql_proxy
        - -instances=pipeline-tutorial-231718:us-west1-c:postgres-server2=tcp:5432
        #- -instances=$GCP_PROJECT:$GCP_REGION:$GCP_SQL_SERVER=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: my-secrets-volume
          readOnly: true
      volumes:
      - name: my-secrets-volume
        secret:
          secretName: cloudsql-instance-credentials
