apiVersion: batch/v1
kind: Job
metadata:
  name: job-migration
  namespace: default
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - args:
        - -c
        - python manage.py migrate && python manage.py runserver 0.0.0.0:8000
        command:
        - /bin/sh
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: dbname
              name: cloudsql-db-credentials
        image: gcr.io/pipeline-tutorial-231718/pipeline:8477eb9bd4ff0476e2eb9956226b862e0d93d627
        name: django-migration-container
        ports:
        - containerPort: 8000
      - command:
        - /cloud_sql_proxy
        - -instances=pipeline-tutorial-231718:us-west1-c:postgres-server2=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: my-secrets-volume
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: my-secrets-volume
        secret:
          secretName: cloudsql-instance-credentials
