kind: Service
apiVersion: v1
metadata:
  name: django-lb
  namespace: default
spec:
  selector:
    app: django-container
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer