apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-231718/pipeline:0bb20d13e1d881e480f5ad933382e4d0fcb761a0
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
