apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: django
  name: django
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-credentials
        - name: POSTGRES_HOST
          value: postgres-service
        image: gcr.io/pipeline-tutorial-231718/pipeline:8ad823f7176220711e311fc3829fadabf6e698ce
        name: django
        ports:
        - containerPort: 8000
